project:
  type: website
  output-dir: docs
  #resources:
  #  - "teaching/*.html"

website:
  title: "Dennis M. Feehan"
  google-analytics: 
    tracking-id: "G-5W77PPS14P"
    anonymize-ip: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching 
      - href: posts.qmd
        text: Posts
      - href: cv/cv.qmd
        text: CV

format:
  html:
    theme: simplex
    css: styles.css
    toc: true
    #mainfont: Georgia, serif 
    fontsize: 1em

editor: source

