---
title: ""
---

My research interests lie primarily at the intersection of social networks,
demography, and quantitative methodology.
Some themes in my work have included developing new sampling methods for learning about
hidden and hard-to-reach populations;
understanding health and mortality;
and computational social science.


#### **Working/Recent papers**  

* [Validating survey-based estimates of adult mortality with high-quality vital statistics: Evidence from 27 cities](https://osf.io/preprints/socarxiv/x5ywv)

* [Estimating death rates in complex humanitarian emergencies using the network survival method](https://osf.io/preprints/socarxiv/4efdt)  
  
* [New Data Sources for Demographic Research](https://onlinelibrary.wiley.com/journal/17284457); [preprint](https://osf.io/ybghv)
  

#### **Selected publications** (see [CV](cv/cv.html) for a full list):

* [Estimating adult death rates from sibling histories: A network approach](https://read.dukeupress.edu/demography/article/58/4/1525/174066/Estimating-Adult-Death-Rates-From-Sibling)

* [Quantifying population contact patterns in the United States during the COVID-19 pandemic](https://doi.org/10.1038/s41467-021-20990-2)

* [Using an online sample to learn about an offline population](http://link.springer.com/article/10.1007/s13524-019-00840-z); [arxiv version](https://arxiv.org/abs/1902.08289)

* [The network survival method for estimating adult mortality: Evidence from a survey experiment in Rwanda](https://link.springer.com/article/10.1007/s13524-017-0594-y)

* [Generalizing the Network Scale-Up Method: A New Estimator for the Size of Hidden Populations](https://doi.org/10.1177/0081175016665425)

::: {.callout-note appearance='simple' icon=false collapse='true'}
  
#### **Software**

Software packages I have developed for various research projects:


* [`siblingsurvival`](https://github.com/dfeehan/siblingsurvival) - Estimating adult death rates from sibling histories, especially those collected by the [Demographic and Health Surveys](https://dhsprogram.com/).

* [`surveybootstrap`](https://github.com/dfeehan/surveybootstrap) - Methods for estimating sampling uncertainty from data collected via complex
sampling designs, such as household surveys.

* [`networkreporting`](https://github.com/dfeehan/networkreporting) - Methods for estimating group size and prevalence from network reports; includes routines for network scale-up, generalized network scale-up, and network survival.

* [`mortfit`](https://github.com/dfeehan/mortfit) - Fitting mortality hazard models, with special attention to humans at very old ages

* [`nrsimluatr`](https://github.com/dfeehan/nrsimulatr)  - Tools for simulating reporting networks, useful in developing and evaluating network reporting methods.

* [`calibratr`](https://github.com/dfeehan/calibratr)  - Wrappers to make  calibration with the `survey` package easier

:::

::: {.callout-note appearance='simple' icon=false collapse='true'}
  
#### **Data**

Datasets related to some of my papers.  
  
* Replication Data for: Survey Methods for Estimating the Size of Weak-Tie Personal Networks <https://doi.org/10.7910/DVN/W2B1V0>

* Replication Data for: Quantifying population contact patterns in the United States during the COVID-19 pandemic <https://doi.org/10.7910/DVN/M74AJ4>

* Replication Data for: Quantity vs. quality: A survey experiment to improve the network scale-up method <https://doi.org/10.7910/DVN/CCC6HF>

* Replication Data for: Generalizing the Network Scale-Up Method: A New Estimator for the Size of Hidden Populations <https://doi.org/10.7910/DVN/HHAUDF>

* Replication Data for: The network survival method for estimating adult mortality: Evidence from a survey experiment in Rwanda <https://doi.org/10.7910/DVN/GSKQIZ>

* Replication code for "Separating the Signal From the Noise: Evidence for Deceleration in Old-Age Death Rates." Demography 55.6 (2018): 2025-2044. <https://github.com/dfeehan/oldage-paper-code-released>

<!--

NOT YET HERE:
- AGGREGATION 
- ALL
- Ethan's paper
- MRP paper
- others?

* Replication Data for: Evaluating primary and booster vaccination prioritization strategies for COVID-19 by age and high-contact employment status using data from contact surveys <https://doi.org/10.7910/DVN/K8YPVZ>

* Replication code for 

-->

:::

