---
title: ""
---

#### Currently teaching

* Spring 2023 - No classes this semester
  

::: {.callout-note appearance='simple' icon=false collapse='true'}
  
#### Previously taught

* Fall 2023: [Demography 180: Social networks (undergrad)](https://www.dennisfeehan.org/demog180-fa2023)
* Fall 2023: [Demography 280/Sociology 273N: Social networks (grad)](teaching/2023fa_demog280.html)
* Fall 2022: [Demography 180: Social networks (undergrad)](teaching/2022fa_demog180.html)
* Fall 2022: [Demography 280/Sociology 273N: Social networks (grad)](teaching/2022fa_demog280.html)
* Fall 2022: Grad seminar on developing research papers 
* Spring 2022: on parental leave
* Fall 2021: [Demography 180: Social networks (undergrad)](teaching/2021fa_demog180.html)
* Fall 2021: [Demography 280/Sociology 273N: Social networks (grad)](teaching/2021fa_demog280.html)
* Spring 2021: [Data 88: Data science and demography (Connector course)](teaching/2021sp_data88.html)
* Fall 2020: [Demography 280/Sociology 273N: Social networks (grad)](teaching/2020fa_demog280.html)
* Spring 2020: on parental leave
* Fall 2019: [Demography 260: Field methods and research design](teaching/2019fa_demog260.html)
* Spring 2019: [Demography 180: Social networks (undergrad)](teaching/2019sp_demog180.html)
* Spring 2019: [Demography 260/Sociology 273N: Social networks (grad)](teaching/2019sp_demog260.html)
* Fall 2018: [L&S 88 - Data Science Connector: Demography (undergrad)](teaching/2018fa_ls88.html)
* Spring 2018: [Demography 180: Social networks (undergrad)](teaching/2018sp_demog180.html)
* Spring 2018: [Demography 260: Social networks (grad)](teaching/2018sp_demog260.html)
* Fall 2017: [L&S 88 - Data Science Connector: Social networks](teaching/2017fa_ls88.html)
* Spring 2017: [Demography 260: Social networks](teaching/201701_demog260.html)
* Fall 2016: [L&S 88 - Data Science Connector: Social networks](teaching/2016fa_ls88.html)
* Spring 2016: [Demography 260: Social networks](teaching/201601_demog260.html)

:::